# Generated by Django 3.0.7 on 2021-01-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210108_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Equipe',
        ),
    ]
