# Generated by Django 3.0.7 on 2021-01-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210109_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipe',
            new_name='Team',
        ),
    ]
