# Generated by Django 3.0.7 on 2021-01-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210109_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Antananarivo', 'Antananarivo'), ('Tamatave', 'Tamatave'), ('Antsirabe', 'Antsirabe'), ('FFianarantsoa', 'Fianarantsoa'), ('Majunga', 'Majunga'), ('Tulear', 'Tulear'), ('Diego-Suerez', 'Diego-Suerez'), ('Antanifotsy', 'Antanifotsy'), ('Ambovombe', 'Ambovombe'), ('Amparafaravola', 'Amparafaravola'), ('Tolanaro', 'Tolanaro'), ('Ambatondrazaka', 'Ambatondrazaka'), ('Mananara Nord', 'Mananara Nord'), ('Soavinandrina', 'Soavinandrina'), ('Mahanoro', 'Mahanoro'), ('Soanierana Ivongo', 'Soanierana Ivongo'), ('Faratsio', 'Faratsio'), ('Nosy Varika', 'Nosy Varika'), ('Vavatenina', 'Vavatenina'), ('Morondava', 'Morondava'), ('Manakara', 'Manakara'), ('Antalaha', 'Antalaha'), ('Sambava', 'Sambava'), ('Marovoay', 'Marovoay'), ('Ambanja', 'Ambanja'), ('Ambositra', 'Ambositra')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('ANTANANARIVO', 'Antananarivo'), ('TOAMASINA', 'Tamatave'), ('FIANARANTSOA', 'Fianarantsoa'), ('MAHAJANGA', 'Majunga'), ('TOLIARY', 'Tulear'), ('ANTSIRANANA', 'Diego-Suerez')], max_length=100),
        ),
    ]
